chore: Error Messages C4 fixes and normalization (SC-2036)
maple-labs/maple-core pull request #365
Opened 2021-04-24 06:23 UTC by deluca-mike

# Description

Rectify error-messsage-related issues raised by C4 and and normalize error messages code-wide.

Clubhouse: https://app.clubhouse.io/maplefinance/story/2036/maple-core-c4-error-messages

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog

- C4 error message issues 62, 63, 65 (see commit description for links)
- Standardized require error messages as "CONTRACT_ABBREVIATION:MESSAGE"
- Standardized all access error messages as "CALLER_NOT_X[_OR_Y]"
- Added missing error messages for SafeMath contracts
- Fixed error message typo in LiquidityLocker contract
- Normalized all "_LIQUIDITY_" to "_LIQ_" in error messages
- Differentiated "NOT_ALLOWED" error messages

## Function Signature Changes

## Features 

## Events

2021-04-24 17:10 UTC, lucas-manuel commented
@xhad would these error message abbreviations cause any issues for the offchain team?

2021-04-26 13:10 UTC, satyamakgec submitted a review, later dismissed

2021-04-26 15:43 UTC, lucas-manuel requested changes
Small changes

2021-04-26 15:43 UTC, lucas-manuel commented on contracts/LoanFactory.sol
> +        loans[loansCreated]   = loanAddress;
`=` alignment

2021-04-26 15:43 UTC, lucas-manuel commented on contracts/library/LoanLib.sol
> +        require(token != liquidityAsset && token != address(0), "L:INVALID_TOKEN");
Lets align these error messages

2021-04-26 16:14 UTC, lucas-manuel submitted a review, later dismissed
LGTM, gonna let CI run.

2021-04-26 17:42 UTC, lucas-manuel submitted a review, later dismissed

2021-04-26 17:44 UTC, lucas-manuel commented on contracts/Pool.sol
> +        // TODO: Discuss with offchain team about requirements for return
This can be taken out now that we've merged the TODOs PR

2021-04-26 17:47 UTC, merged