Migrate/Distribute tests
maple-labs/maple-core pull request #409
Opened 2021-06-01 10:47 UTC by satyamakgec

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
## Function Signature Changes

## Features 

## Events

2021-06-01 14:51 UTC, lucas-manuel approved these changes, later dismissed
LGTM 👍

2021-06-02 08:11 UTC, deluca-mike requested changes

2021-06-02 08:11 UTC, deluca-mike commented on contracts/core/chainlink-oracle/v1/test/ChainLinkOracle.t.sol
> +import "../../../../test/TestUtil.sol";
I'd prefer a remapping to a "global" `tests` directory, so we can avoid all of these ugly deep relative imports.

2021-06-02 08:11 UTC, deluca-mike commented on contracts/core/late-fee-calculator/v1/test/LateFeeCalc.t.sol
> +import "../../../../test/TestUtil.sol";
Ditto for this and all others.

2021-06-02 08:11 UTC, deluca-mike commented on contracts/core/pool/v1/test/PoolCustodial.t.sol
> +import "../../../../test/user/Custodian.sol";
Ditto.

2021-06-02 08:11 UTC, deluca-mike commented on test.sh
> +        v) version=${OPTARG};;
💯

2021-06-02 15:57 UTC, deluca-mike approved these changes

2021-06-02 15:57 UTC, merged