fee: Implement Annualized Establishment Fees based on MIP spec (SC-2755)
maple-labs/maple-core pull request #421
Opened 2021-07-05 10:25 UTC by satyamakgec

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
## Function Signature Changes

## Features 

## Events

2021-07-05 15:30 UTC, lucas-manuel requested changes
Small comments/questions

2021-07-05 15:30 UTC, lucas-manuel commented on config-dev.json
> +    "contracts/core/loan/v1/LoanV1.sol": {
I'm going to review this and ignore the contract name change because we need to have a discussion about it.

2021-07-05 15:30 UTC, lucas-manuel commented on contracts/core/loan/v1/LoanV1.sol
>      function drawdown(uint256 amt) external override {
I think it makes sense to split out all of this logic into an internal function that takes `treasuryFee` and `investorFee` and `amt` as params. Then you could just calculate them in the first two lines using `amt` and then pass them in. The requires would happen after but I think that's okay honestly.

2021-07-05 15:30 UTC, lucas-manuel commented on contracts/core/loan/v2/LoanV2.sol
> +contract LoanV2 is LoanV1 {
How does this compile without an import of LoanV1?

2021-07-05 15:30 UTC, lucas-manuel commented on contracts/core/loan/v2/LoanV2.sol
> +    function drawdown(uint256 amt) external override {
Use internal function mentioned above here

2021-07-13 13:23 UTC, deluca-mike commented
I'll rebase this onto the LoanV2 PR, which will come after the relative and explicit import PR, which will come after the AAVE PR.

2021-11-18 16:58 UTC, closed without merging